
name: build

on:
  push:
    branches: 
      - demo
    paths:
      - '.github/workflows/backend.yml'
      - 'backend/**'
    

jobs:
  job1:
    name: Build and Push All Service

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean package -DskipTests
    -
      name: Login to ghcr.io
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.USERNAME_GITHUB }}
        password: ${{ secrets.TOKEN_GITHUB }}
    -
      name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: backend
        push: true
        tags: ghcr.io/miryalavenkat/backend:latest

    - 
      name: Deploy to EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        EC2_IP_ADDRESS: ${{ secrets.EC2_IP_ADDRESS }}
      run: |

        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        
        ssh -o StrictHostKeyChecking=no  ubuntu@$EC2_IP_ADDRESS "docker rm -sf backend; docker rmi ghcr.io/miryalavenkat/backend:latest ; docker compose up -d "
    